---
title: "Обработка ошибок и исключений с помощью Azure Logic Apps | Документация Майкрософт"
description: "Сведения об обработке ошибок и исключений в Azure Logic Apps"
services: logic-apps
documentationcenter: .net,nodejs,java
author: jeffhollan
manager: anneta
editor: 
ms.assetid: e50ab2f2-1fdc-4d2a-be40-995a6cc5a0d4
ms.service: logic-apps
ms.devlang: multiple
ms.topic: article
ms.tgt_pltfrm: na
ms.workload: integration
ms.date: 10/18/2016
ms.author: LADocs; jehollan
ms.openlocfilehash: 9af2f71b3d288cc6f4e271d0915545d43a1249bc
ms.sourcegitcommit: f537befafb079256fba0529ee554c034d73f36b0
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 07/11/2017
---
# <a name="handle-errors-and-exceptions-in-azure-logic-apps"></a>Обработка ошибок и исключений в Azure Logic Apps

Azure Logic Apps предоставляет большой набор средств и шаблонов, позволяющих обеспечить надежные и устойчивые к сбоям интеграции. При использовании любой архитектуры интеграции возникают сложности, связанные с соответствующей обработкой простоя или устранением неполадок, вызванных зависимыми системами. Logic Apps существенно упрощает обработку ошибок, предоставляя средства для устранения ошибок и исключений в рабочих процессах.

## <a name="retry-policies"></a>Политики повтора

Самое простое средство обработки ошибок и исключений — политика повтора. Эта политика определяет, следует ли повторить действие, если время ожидания первоначального запроса истекло или он завершился сбоем (любой запрос с ответом 429 или 5xx). По умолчанию все действия повторяются 4 дополнительных раза с 20-секундным интервалом. То есть, если для первого запроса вернулся ответ `500 Internal Server Error`, обработчик рабочего процесса отправляет повторный запрос по истечении 20 секунд. Если после всех попыток в ответе по-прежнему возвращается исключение или сбой, выполнение рабочего процесса продолжится, а действие будет помечено как `Failed`.

Политику повтора можно задать во **входных данных** определенного действия. Например, вы можете настроить выполнение максимум 4 попыток в течение 1 часа. Дополнительные сведения о входных свойствах см. в статье [Workflow actions and triggers for Azure Logic Apps][retryPolicyMSDN] (Действия и триггеры рабочего процесса для Azure Logic Apps).

```json
"retryPolicy" : {
      "type": "<type-of-retry-policy>",
      "interval": <retry-interval>,
      "count": <number-of-retry-attempts>
    }
```

Если необходимо, чтобы для выполнения HTTP-действия предпринималось 4 попытки с 10-минутным интервалом между ними, задайте следующее определение:

```json
"HTTP": 
{
    "inputs": {
        "method": "GET",
        "uri": "http://myAPIendpoint/api/action",
        "retryPolicy" : {
            "type": "fixed",
            "interval": "PT10M",
            "count": 4
        }
    },
    "runAfter": {},
    "type": "Http"
}
```

Дополнительные сведения о поддерживаемом синтаксисе см. в разделе о политике повторения в [этой статье][retryPolicyMSDN].

## <a name="catch-failures-with-the-runafter-property"></a>Перехват ошибок с помощью свойства RunAfter

Каждое действие приложения логики объявляет, какие действия должны завершаться перед началом определенного действия (наподобие упорядочения действий рабочего процесса). Это упорядочение задается с помощью свойства `runAfter` в определении действия. Данное свойство является объектом, описывающим, какие действия и состояния действий необходимы для выполнения определенного действия. По умолчанию все действия, добавленные с помощью конструктора приложений логики, получают свойство `runAfter` предыдущего шага, если он получил состояние `Succeeded`. Однако это значение можно изменить таким образом, чтобы действия срабатывали, если предыдущие действия получили состояние `Failed`, `Skipped` или оба. Чтобы добавить элемент в указанный раздел служебной шины после сбоя определенного действия `Insert_Row`, необходимо использовать следующую конфигурацию `runAfter`:

```json
"Send_message": {
    "inputs": {
        "body": {
            "ContentData": "@{encodeBase64(body('Insert_Row'))}",
            "ContentType": "{ \"content-type\" : \"application/json\" }"
        },
        "host": {
            "api": {
                "runtimeUrl": "https://logic-apis-westus.azure-apim.net/apim/servicebus"
            },
            "connection": {
                "name": "@parameters('$connections')['servicebus']['connectionId']"
            }
        },
        "method": "post",
        "path": "/@{encodeURIComponent('failures')}/messages"
    },
    "runAfter": {
        "Insert_Row": [
            "Failed"
        ]
    }
}
```

Обратите внимание, что для свойства `runAfter` настроено срабатывание, если действие `Insert_Row` имеет состояние `Failed`. Чтобы выполнить действие, если состояние действия `Succeeded`, `Failed` или `Skipped`, используйте такой синтаксис:

```json
"runAfter": {
        "Insert_Row": [
            "Failed", "Succeeded", "Skipped"
        ]
    }
```

> [!TIP]
> Действия, успешно завершенные после сбоя предыдущего действия, будут помечены как `Succeeded`. Таким образом, если перехватить все ошибки в рабочем процессе, само выполнение помечается как `Succeeded`.

## <a name="scopes-and-results-to-evaluate-actions"></a>Области и результаты для оценки действий

Точно так же, как можно запускать выполнение после отдельных действий, можно сгруппировать действия внутри [области](../logic-apps/logic-apps-loops-and-scopes.md), которая действует как логическая группа действий. Области можно эффективно использовать как для организации действий приложения логики, так и для выполнения статистических вычислений на основе состояния области. Сама область получает определенное состояние после завершения в ней всех действий. Состояние области определяется теми же критериями, которые используются для выполнения. Если состояние последнего действия в ветви выполнения — `Failed` или `Aborted`, область получит состояние `Failed`.

Чтобы запускать определенные действия для обнаружения любых сбоев, произошедших в области, вы можете использовать свойство `runAfter` для области с состоянием `Failed`. Исходя из этого, можно создать отдельное действие для перехвата ошибок, в случае если *какое-либо* действие в области завершилось сбоем.

### <a name="getting-the-context-of-failures-with-results"></a>Получение контекста сбоев в результатах

Хотя перехват ошибок в области очень эффективен, вам также может понадобиться контекст, чтобы понять, какие действия завершились сбоем, и узнать возвращенные ошибки и коды состояния. Функция рабочего процесса `@result()` выводит контекст о результате всех действий в области.

`@result()` принимает один параметр, имя области, и возвращает массив результатов всех действий в этой области. Объекты действия включают в себя те же атрибуты, что и объект `@actions()` , в том числе время начала и окончания действия, состояние действия, входные и выходные данные действия, а также идентификаторы корреляции действия. Чтобы отправить контекст любых действий, завершившихся сбоем в области, вы можете легко связать функцию `@result()` со свойством `runAfter`.

Чтобы выполнять действие *для каждого* действия в области с состоянием `Failed`, выполните фильтрацию массива результатов по действиям, которые завершились сбоем, что позволит вам связать `@result()` с действием **[Фильтр массива](../connectors/connectors-native-query.md)** и циклом **[ForEach](../logic-apps/logic-apps-loops-and-scopes.md)**. Можно настроить выполнение действия для каждой ошибки в отфильтрованном массиве результатов с помощью цикла **ForEach** . Ниже представлен пример с подробным описанием под ним. В этом примере отправляется запрос HTTP POST, для которого будут возвращены завершившиеся сбоем действия в области `My_Scope`.

```json
"Filter_array": {
    "inputs": {
        "from": "@result('My_Scope')",
        "where": "@equals(item()['status'], 'Failed')"
    },
    "runAfter": {
        "My_Scope": [
            "Failed"
        ]
    },
    "type": "Query"
},
"For_each": {
    "actions": {
        "Log_Exception": {
            "inputs": {
                "body": "@item()['outputs']['body']",
                "method": "POST",
                "headers": {
                    "x-failed-action-name": "@item()['name']",
                    "x-failed-tracking-id": "@item()['clientTrackingId']"
                },
                "uri": "http://requestb.in/"
            },
            "runAfter": {},
            "type": "Http"
        }
    },
    "foreach": "@body('Filter_array')",
    "runAfter": {
        "Filter_array": [
            "Succeeded"
        ]
    },
    "type": "Foreach"
}
```

Подробно рассмотрим приведенный выше пример.

1. Чтобы получить результат всех действий в области `My_Scope`, действие **Фильтр массива** выполняет фильтрацию `@result('My_Scope')`.

2. Условием отбора для действия **Фильтр массива** является любой элемент `@result()` с состоянием `Failed`. Это условие применяет к массиву фильтр для получения массива с результатами действий, завершившихся сбоем, в области `My_Scope`.

3. Затем выполняется действие **For Each** для данных, полученных в результате выполнения действия **Фильтровать массив**. При этом выполняется действие *для каждого* ранее отфильтрованного результата действия, завершившегося сбоем.

    Если определенное действие в области завершилось сбоем, действия в цикле `foreach` выполняются не более одного раза. 
    Многие завершившиеся сбоем действия приведут к выполнению только одного действия на сбой.

4. Затем отправляется запрос HTTP POST для текста ответа элемента `foreach` или `@item()['outputs']['body']`. Форматы элемента `@result()` и `@actions()` совпадают, поэтому они могут быть проанализированы одинаковым образом.

5. В код выше включены два пользовательских заголовка с именем завершившегося сбоем действия `@item()['name']` и идентификатором отслеживания клиента выполнения со сбоем `@item()['clientTrackingId']`.

Ниже приведен пример (для справочных целей) отдельного элемента `@result()` с отображением свойств `name`, `body` и `clientTrackingId`, проанализированных в примере выше. Вне цикла `foreach` `@result()` возвращает массив этих объектов.

```json
{
    "name": "Example_Action_That_Failed",
    "inputs": {
        "uri": "https://myfailedaction.azurewebsites.net",
        "method": "POST"
    },
    "outputs": {
        "statusCode": 404,
        "headers": {
            "Date": "Thu, 11 Aug 2016 03:18:18 GMT",
            "Server": "Microsoft-IIS/8.0",
            "X-Powered-By": "ASP.NET",
            "Content-Length": "68",
            "Content-Type": "application/json"
        },
        "body": {
            "code": "ResourceNotFound",
            "message": "/docs/folder-name/resource-name does not exist"
        }
    },
    "startTime": "2016-08-11T03:18:19.7755341Z",
    "endTime": "2016-08-11T03:18:20.2598835Z",
    "trackingId": "bdd82e28-ba2c-4160-a700-e3a8f1a38e22",
    "clientTrackingId": "08587307213861835591296330354",
    "code": "NotFound",
    "status": "Failed"
}
```

Выражения, представленные выше, можно использовать для выполнения различных шаблонов обработки исключений. Вы можете настроить выполнение одного действия обработки исключений вне области, которое принимает весь отфильтрованный массив сбоев, и удалить цикл `foreach`. Можно также включить другие полезные свойства из ответа `@result()`, приведенного выше.

## <a name="azure-diagnostics-and-telemetry"></a>Система диагностики и телеметрия Azure

Приведенные выше шаблоны — эффективный способ обработки ошибок и исключений в выполнении. Однако можно также обнаруживать отдельные ошибки и реагировать на них независимо от выполнения. 
[Система диагностики Azure](../logic-apps/logic-apps-monitor-your-logic-apps.md) предоставляет простой способ отправки всех событий рабочего процесса (включая все состояния выполнений и действий) в учетную запись хранения Azure или концентратор событий Azure. Вы можете отслеживать журналы и метрики или публиковать их в любом средстве мониторинга для оценки состояния выполнения. К примеру, можно направлять поток всех событий через концентратор событий Azure в [Stream Analytics](https://azure.microsoft.com/services/stream-analytics/). В Stream Analytics можно написать активные запросы для получения сведений об отклонении, средних показателей или сбоев из журналов диагностики. Stream Analytics может выводить данные в другие источники данных, такие как очереди, разделы, SQL, Azure Cosmos DB и Power BI.

## <a name="next-steps"></a>Дальнейшие действия

* [Сценарий обработки исключений и ведения журнала ошибок для приложений логики](../logic-apps/logic-apps-scenario-error-and-exception-handling.md)
* [Примеры использования Logic Apps и распространенные сценарии](../logic-apps/logic-apps-examples-and-scenarios.md)
* [Создание шаблонов для развертывания приложений логики и управления выпусками](../logic-apps/logic-apps-create-deploy-template.md)
* [Создание и развертывание приложений логики в Visual Studio](logic-apps-deploy-from-vs.md)

<!-- References -->
[retryPolicyMSDN]: https://docs.microsoft.com/rest/api/logic/actions-and-triggers#Anchor_9
